### ISSUE TITLE
Secrets file not found

### ISSUE THREAD

**Issue by lukkzien** [lperezmo/real-time-translator#1]
I'm getting the error "Secrets file not found"

**Comment by lperezmo** [comment]
I tried it in a couple different browsers and didn’t get this error, so it might have been an issue with the hosting platform (streamlit cloud). If you try it again and you keep getting an error it would be helpful to know the platform and browser you are using so I can troubleshoot it, thanks!

**Comment by DrKinGpinG** [comment]
Same issue.
The error occures while trying to start the program.

PS D:\real-time-translator> python .\app.py
2023-12-02 08:42:10.717
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run .\app.py [ARGUMENTS]
Traceback (most recent call last):
  File "D:\real-time-translator\app.py", line 78, in <module>
    main()
  File "D:\real-time-translator\app.py", line 30, in main
    openai.api_key = st.secrets["OPENAI_API_KEY"]
  File "C:\Users\blabla\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\secrets.py", line 305, in __getitem__
    value = self._parse(True)[key]
  File "C:\Users\blabla\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\secrets.py", line 214, in _parse
    raise FileNotFoundError(err_msg)
FileNotFoundError: No secrets files found. Valid paths for a secrets.toml file are: C:\Users\blabla\.streamlit\secrets.toml, D:\real-time-translator\.streamlit\secrets.toml

Looks like login credentials for streamlit are missing maybe?

**Comment by lperezmo** [comment]
Hi guys, I see now, you were trying to run it locally. You would need to create a file called `secrets.toml` inside of the `.streamlit` folder. The file should have the following contents:

```
OPENAI_API_KEY='your-key'
```
You could also set it directly on the code by setting `openai.api_key = "your-key"`

For open source alternatives to OpenAI see [whisper_cpp](https://github.com/ggerganov/whisper.cpp), it's awesome.
